[build]
command = "npm run build"
functions = "functions"
publish = "dist"

[dev]
autoLaunch = false
envFiles = [".env.local"]
functionsPort = 8080

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
