name: CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    test:
        name: Unit and E2E
        runs-on: ubuntu-latest
        env:
            ABLR_API_URL: ${{ secrets.ABLR_API_URL }}
            MY_STORE_ID: ${{ secrets.MY_STORE_ID }}
            MY_SECRET_KEY: ${{ secrets.MY_SECRET_KEY }}
            SG_STORE_ID: ${{ secrets.SG_STORE_ID }}
            SG_SECRET_KEY: ${{ secrets.SG_SECRET_KEY }}

        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: "16"
            - name: Install dependencies
              run: npm install --legacy-peer-deps
            - name: Install Playwright
              run: npx playwright install --with-deps
            - name: Run tests
              run: npm run test:ci
            - name: Run e2e tests
              run: npm run e2e
